name: Build Stage
run-name: ${{ github.actor }} building stage ${{ github.event.number }}
on:
  pull_request:
    types: [opened, reopened]
jobs:
  build_application:
    name: Build Web Application
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get install unzip php php-cli sqlite3
          curl -fsSL https://bun.sh/install | bash
          curl -sS https://getcomposer.org/installer | php
          mkdir -p ~/.local/bin
          sudo mv composer.phar ~/.local/bin/composer
      - name: Bundle & Optimize Web Application
        env:
          PATH: ~/.bun/bin:~/.local/bin:/usr/local/bin:$PATH
        run: |
          composer install
          php artisan optimize
          bun install
          bun run build
      - name: Post-Build
        run: |
          echo "Completed!"
          pwd
          ls -l
